spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/oes
    username: postgres
    password: postgres
  jpa:
    show-sql: true



# 自定义jwt key
jwt:
  #JWT存储的请求头
  tokenHeader: Authorization
  #JWT加解密使用的密钥
  secret: bwang
  #JWT的超期限时间(60*60*24)
  expiration: 604800
  #JWT负载中拿到开头
  tokenHead: Bearer

springfox:
  documentation:
    enabled: true
    swagger-ui:
      enabled: true